b2z1_mujoco_bridge_node:
  ros__parameters:
    network_interface: "lo"
    ramp_duration_sec: 3.5
    ground_support_kp_scale: 0.28
    ground_support_kd_scale: 0.45
    b2_stand_target_1_q: [
      0.0, 1.36, -2.65,
      0.0, 1.36, -2.65,
      0.2, 1.36, -2.65,
      0.2, 1.36, -2.65
    ]
    b2_stand_target_2_q: [
      0.0, 0.67, -1.3,
      0.0, 0.67, -1.3,
      0.0, 0.67, -1.3,
      0.0, 0.67, -1.3
    ]
    b2_stand_target_3_q: [
      0.0, 1.36, -2.65,
      0.0, 1.36, -2.65,
      0.0, 1.36, -2.65,
      0.0, 1.36, -2.65
    ]
    b2_stand_target_4_q: [
      -0.5, 1.36, -2.65,
       0.5, 1.36, -2.65,
      -0.5, 1.36, -2.65,
       0.5, 1.36, -2.65
    ]
    b2_stand_phase_durations: [
      1.0,
      1.8,
      2.0,
      2.2,
      1.0
    ]
    b2_down_q: [
      0.0, 1.28, -2.8,
      0.0, 1.28, -2.8,
      0.0, 1.28, -2.8,
      0.0, 1.28, -2.8
    ]
    b2_kp_by_joint: [
      260.0, 260.0, 260.0,
      260.0, 260.0, 260.0,
      430.0, 430.0, 430.0,
      430.0, 430.0, 430.0
    ]
    b2_kd_by_joint: [
      7.0, 7.0, 7.0,
      7.0, 7.0, 7.0,
      8.0, 8.0, 8.0,
      8.0, 8.0, 8.0
    ]
    z1_home_q: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    z1_kp_by_joint: [100.0, 100.0, 100.0, 100.0, 10.0, 10.0]
    z1_kd_by_joint: [10.0, 10.0, 10.0, 5.0, 1.0, 1.0]
